# This action will publish the package to npm and create a GitHub release.
name: Release

on:
  # Run `npm run bump` to bump the version and create a git tag.
  push:
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0

      # Update npm to the latest version to enable OIDC
      # Use corepack to install pnpm
      - name: Update npm CLI
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: empty

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: "true"
